settings:
  prefix: '<#4b8eff>&lM<#5286ff>&la<#597eff>&lg<#5f75ff>&ln<#666dff>&le<#6d65fe>&ls<#745dfe>&li<#7a55fe>&lf<#814dfe>&ly <#8844fe>&lD<#8f3cfe>&lu<#9534fe>&ln<#9c2cfe>&lg<#a324fd>&le<#aa1bfd>&lo<#b013fd>&ln<#b70bfd>&ls&r &8・&r'
  top-list-amount: 5
  whitelist-commands:
    - "say"
    - "heal"
    - "feed"
  chest-contents:
    - "APPLE:5:100"
    - "GOLDEN_APPLE:5:25"
    - "PAPER:5:75"
  skill-tools:
    GHOST:
      display: '<#4b8eff>Paralel Ruh'
      material: BOOK
  trigger-type:
    boss:
      title: '<#4b8eff>Zindan Seviyeleri'
    dungeons:
      title: '<#4b8eff>Aktif Keşif Zindanları'
    title: '<#4b8eff>Keşif Zindanları'
    custom-gui-texture: _iainternal:blank_menu
    defaults:
      display: '<#4b8eff>&l#dungeon'
      material: NETHERITE_AXE
      lore:
        - ''
        - '&fDurum: &e#status'
        - ''
        - '&fSüre: <#4b8eff>#play_time'
        - '&fToplam <#4b8eff>#total_level &fseviyeden oluşuyor...'
        - ''
  challange:
    title: '<#4b8eff>Meydan Okumalar'
    custom-gui-texture: _iainternal:blank_menu
    defaults:
      display: '<#4b8eff>&l#dungeon'
      material: DIAMOND_AXE
      lore:
        - ''
        - '&fDurum: &e#status'
        - ''
        - '&fYaratık: <#4b8eff>#boss_name'
        - '&fCanı: <#4b8eff>#boss_health'
        - '&fSüre: <#4b8eff>#play_time'
        - ''
        - '&fMeydan okumalarda herhangi bir puan kazanmaz ya da kaybetmezsin.'
        - ''
  profile:
    title: '<#4b8eff>Zindan Profilin'
    custom-gui-texture: _iainternal:blank_menu
    items:
      player:
        material: DIAMOND
        display: "<#4b8eff>Hakkında"
        slot: 24
        lore:
          - ''
          - '&fPuanın: <#4b8eff>#point'
          - '&fEn son bulunduğun zindan: <#4b8eff>#last_dungeon'
          - ''
      ranks:
        material: LADDER
        display: "<#4b8eff>Sıralama"
        slot: 20
        lore:
          - ''
          - '<#4b8eff>En iyi 10 oyuncu'
          - '&f#ranks'
          - ''
      stats:
        material: BOOK
        display: "<#4b8eff>Genel İstatistikler"
        slot: 13
        lore:
          - ''
          - '&fÖlme: <#4b8eff>#death'
          - '&fÖldürme: <#4b8eff>#kill'
          - '&fKazanılan maç: <#4b8eff>#win'
          - '&fKaybedilen maç: <#4b8eff>#lose'
          - '&fOynanan maç: <#4b8eff>#total'
          - ''
  countdown-warnings:
    30:
      warn-at: 30
    10:
      warn-at: 10
  boss:
    title: '<#4b8eff>Yaratık güncelleme ekranı'
    drops:
      title: '<#4b8eff>Düşen eşyaları güncelliyorsun...'
  genus:
    title: '<#4b8eff>Tür seçim ekranı'
    custom-gui-texture: _iainternal:blank_menu
  market:
    title: '<#4b8eff>Zindan Marketi'
  minimal-options:
    send-damage-title: true
    teleport-delay-for-sending-spawn: 3
  defaults:
    dungeon-world: "Magnesify"
    last-dungeon: "Henüz bir zindana giriş yapmamış."
  sounds:
    starting: ENTITY_PLAYER_LEVELUP
    entering: ENTITY_PLAYER_LEVELUP
  custom-commands:
    leave: ayrıl
    join: gir
    market: market
    stats: istatistikler
    profile: profil
    dungeons: zindanlar
    challanges: meydanokumalar
  holders:
    full: "Dolu"
    empty: "Boş"
    not-selected: "Seçilmemiş"
    name: "İsim"
    category: "Kategori"
    boss_id: "Boss kimliği"
    level: "Seviye"
    play-time: "Oynama Süresi (Saniye)"
    start-time: "Başlama Süresi (Saniye)"
    none: "Yok"